---
- name: Converge
  hosts: all
  become: yes
  vars:
    vmalert_install_download_to_control: true
  tasks:
    - name: "Include vmalert"
      ansible.builtin.include_role:
        name: "vmalert"
