# handlers file for VictoriaMetrics
---
- name: "Restart VMalert service {{ vmalert_service_name }}"
  become: true
  ansible.builtin.service:
    name: "{{ vmalert_service_name }}"
    state: restarted
  ignore_errors: '{{ ansible_check_mode }}'
  listen: "Restart VMalert service"
