- name: Ensure license key is provided
  ansible.builtin.assert:
    that: vlsingle_license_key != "" or vlsingle_license_key_file != ""
    msg: Either license key or license key file location must be provided.
  when: vlsingle_enterprise | bool

- name: Ensure only one of key or file is provided
  ansible.builtin.assert:
    that: vlsingle_license_key_file == ""
    msg: Only one of license key or license key file must be provided.
  when:
    - vlsingle_enterprise | bool
    - vlsingle_license_key != ""


- name: Ensure only one of key or file is provided
  ansible.builtin.assert:
    that: vlsingle_license_key == ""
    msg: Only one of license key or license key file must be provided.
  when:
    - vlsingle_enterprise | bool
    - vlsingle_license_key_file != ""


- name: Add license key parameter to service config
  ansible.builtin.set_fact:
    vlsingle_service_args: "{{ vlsingle_service_args | combine({'license': vlsingle_license_key}) }}"
  when:
    - vlsingle_enterprise | bool
    - vlsingle_license_key != ""


- name: Add license key parameter to service config
  ansible.builtin.set_fact:
    vlsingle_service_args: "{{ vlsingle_service_args | combine({'licenseFile': vlsingle_license_key_file}) }}"
  when:
    - vlsingle_enterprise | bool
    - vlsingle_license_key_file != ""
