---
namespace: "victoriametrics"
name: "cluster"
version: "{{ref}}"
readme: "README.md"
authors:
    - "Zakhar Bessarab <zekker6@gmail.com>"
    - "bykvaadm <info@bykvaadm.ru>"
license:
    - "Apache-2.0"
tags:
    - victoriametrics
    - monitoring
repository: "https://github.com/VictoriaMetrics/ansible-playbooks"
build_ignore:
    - .git
    - .github
    - build
    - inventory_example
    - Vagrantfile
    - '*.tar.gz'
homepage: "https://github.com/VictoriaMetrics/ansible-playbooks"
documentation: "https://github.com/VictoriaMetrics/ansible-playbooks"
issues: "https://github.com/VictoriaMetrics/ansible-playbooks/issues"