---
- name: Copy VLagent systemd unit file
  ansible.builtin.template:
    src: vlagent.service.j2
    dest: "/etc/systemd/system/{{ vlagent_service_name }}.service"
    owner: root
    group: root
    mode: "0644"
  register: config_template
  no_log: True
  notify: Restart VLagent service

- name: Daemon-reload VLagent service # noqa: no-handler
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
  when: config_template is changed
  changed_when: config_template is changed

- name: Ensure VLagent service is enabled on boot
  become: true
  ansible.builtin.systemd:
    name: "{{ vlagent_service_name }}"
    enabled: true
