---
- name: Converge
  hosts: all
  become: yes
  vars:
    vmsingle_data_dir: "/tmp/victoria-metrics/"
    vmsingle_install_download_to_control: true
    vmsingle_service_args:
      storageDataPath: "{{ vmsingle_data_dir }}"
  tasks:
    - name: "Include vmsingle"
      ansible.builtin.include_role:
        name: "vmsingle"
