---
lint: |
  yamllint .
  ansible-lint .


dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: vmsingle-debian11
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian11}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible

verifier:
  name: ansible
