---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  tasks:
    - name: Check if port 12345 is listening
      ansible.builtin.wait_for:
        port: 12345
        delay: 5
        timeout: 10
        msg: "Timeout waiting for port to respond"
      register: port_check
      ignore_errors: yes

    - name: Validate victoria is listening
      ansible.builtin.assert:
        that: port_check is succeeded

    - name: Check if port 8428 is listening
      ansible.builtin.wait_for:
        port: 8428
        delay: 5
        timeout: 10
        msg: "Timeout waiting for port to respond"
      register: port_check
      ignore_errors: yes

    - name: Validate victoria is listening
      ansible.builtin.assert:
        that: port_check is succeeded
