---
- name: "Systemd | Copy vmstorage systemd unit file"
  ansible.builtin.template:
    src: vmstorage.service.j2
    dest: "/etc/systemd/system/{{ vmstorage_service_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify: Restart vmstorage service

- name: "Systemd | ensure vmstorage service is enabled" # noqa: no-handler
  become: true
  ansible.builtin.systemd:
    name: "{{ vmstorage_service_name }}"
    enabled: true

- name: Prepare configuration dir
  ansible.builtin.file:
    state: directory
    path: "{{ vmstorage_config_dir }}"
    mode: "0751"
    owner: "{{ vmstorage_system_user }}"
    group: "{{ vmstorage_system_group }}"

- name: Configure envflag data file
  ansible.builtin.template:
    dest: "{{ vmstorage_service_envflag_data_file }}"
    src: "vmstorage.conf.j2"
    owner: root
    group: root
    mode: "0600"
  no_log: true
  when: vmstorage_service_envflag_enabled | bool
  notify: Restart vmstorage service

- name: Check envfile presence
  ansible.builtin.stat:
    path: "{{ vmstorage_service_envflag_file }}"
  register: envfile_state
  when: vmstorage_service_envflag_enabled | bool

- name: Setup envfile
  ansible.builtin.file:
    state: touch
    path: "{{ vmstorage_service_envflag_file }}"
    owner: root
    group: root
    mode: "0600"
    access_time: preserve
  when:
    - vmstorage_service_envflag_enabled | bool
    - envfile_state.stat.exists is defined and not envfile_state.stat.exists
  notify: Restart vmstorage service

- name: Prepare data dir
  ansible.builtin.file:
    state: directory
    path: "{{ vmstorage_data_dir }}"
    mode: "0751"
    owner: "{{ vmstorage_system_user }}"
    group: "{{ vmstorage_system_group }}"
