- name: Ensure license key is provided
  ansible.builtin.assert:
    that: vmstorage_license_key != "" or vmstorage_license_key_file != ""
    msg: Either license key or license key file location must be provided.
  when: vmstorage_enterprise | bool

- name: Ensure only one of key or file is provided
  ansible.builtin.assert:
    that: vmstorage_license_key_file == ""
    msg: Only one of license key or license key file must be provided.
  when:
    - vmstorage_enterprise | bool
    - vmstorage_license_key != ""

- name: Ensure only one of key or file is provided
  ansible.builtin.assert:
    that: vmstorage_license_key == ""
    msg: Only one of license key or license key file must be provided.
  when:
    - vmstorage_enterprise | bool
    - vmstorage_license_key_file != ""

- name: Add license key parameter to envflag data
  ansible.builtin.set_fact:
    vmstorage_service_envflag_data: "{{ vmstorage_service_envflag_data | combine({'license': vmstorage_license_key}) }}"
  when:
    - vmstorage_enterprise | bool
    - vmstorage_license_key != ""
    - vmstorage_service_envflag_enabled | bool

- name: Add license key parameter to service args
  ansible.builtin.set_fact:
    vmstorage_service_args: "{{ vmstorage_service_args | combine({'license': vmstorage_license_key}) }}"
  when:
    - vmstorage_enterprise | bool
    - vmstorage_license_key != ""
    - not vmstorage_service_envflag_enabled | bool

- name: Add license key file parameter to envflag data
  ansible.builtin.set_fact:
    vmstorage_service_envflag_data: "{{ vmstorage_service_envflag_data | combine({'licenseFile': vmstorage_license_key_file}) }}"
  when:
    - vmstorage_enterprise | bool
    - vmstorage_license_key_file != ""
    - vmstorage_service_envflag_enabled | bool

- name: Add license key file parameter to service args
  ansible.builtin.set_fact:
    vmstorage_service_args: "{{ vmstorage_service_args | combine({'licenseFile': vmstorage_license_key_file}) }}"
  when:
    - vmstorage_enterprise | bool
    - vmstorage_license_key_file != ""
    - not vmstorage_service_envflag_enabled | bool
