---
- name: Converge
  hosts: all
  become: yes
  vars:
    victoriametrics_data_dir: "/tmp/victoria-logs/"
    victoriametrics_service_args:
      storageDataPath: "{{ victoriametrics_data_dir }}"
  tasks:
    - name: "Include vlsingle"
      ansible.builtin.include_role:
        name: "vlsingle"
