---
- name: Converge
  hosts: all
  become: yes
  vars:
    victoriametrics_enterprise: true
    victoriametrics_license_key_file: "/tmp/vm-license"
    victoriametrics_data_dir: "/tmp/victoria-metrics/"
    victoriametrics_backup_enabled: false
    victoriametrics_service_envflag_enabled: true
    victoriametrics_service_envflag_data:
      - "graphiteListenAddr=127.0.0.1:12345"
    victoriametrics_service_args:
      storageDataPath: "{{ victoriametrics_data_dir }}"
  tasks:
    - name: "Include vmsingle"
      ansible.builtin.include_role:
        name: "vmsingle"
