---
- name: Converge
  hosts: all
  become: yes
  vars:
    vmsingle_enterprise: true
    vmsingle_license_key: "{{ lookup('env', 'VM_LICENSE_KEY') }}"
    vmsingle_license_key_file: "{{ '' if lookup('env', 'VM_LICENSE_KEY') else '/tmp/vm-license' }}"
    vmsingle_data_dir: "/tmp/victoria-metrics/"
    vmsingle_backup_enabled: false
    vmsingle_service_envflag_enabled: true
    vmsingle_service_envflag_data:
      - "graphiteListenAddr=127.0.0.1:12345"
    vmsingle_service_args:
      storageDataPath: "{{ vmsingle_data_dir }}"
  tasks:
    - name: "Include vmsingle"
      ansible.builtin.include_role:
        name: "vmsingle"
