---
- name: Converge
  hosts: all
  become: yes
  vars:
    victoriatraces_data_dir: "/tmp/victoria-traces/"
    victoriatraces_service_args:
      storageDataPath: "{{ victoriatraces_data_dir }}"
  tasks:
    - name: "Include vtsingle"
      ansible.builtin.include_role:
        name: "vtsingle"
