---
dependency:
  name: galaxy
  enabled: false
driver:
  name: docker

platforms:
  - name: vtstorage-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: vtcluster
    groups:
      - vtstorage
  - name: vtstorage-2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: vtcluster
    groups:
      - vtstorage
  - name: vtstorage-3
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: vtcluster
    groups:
      - vtstorage

  - name: vtinsert-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: vtcluster
    groups:
      - vtinsert
  - name: vtinsert-2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: vtcluster
    groups:
      - vtinsert

  - name: vtselect-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: vtcluster
    groups:
      - vtselect
  - name: vtselect-2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: vtcluster
    groups:
      - vtselect

  - name: vmauth-vt-1
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: vtcluster
    groups:
      - vmauth
  - name: vmauth-vt-2
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: vtcluster
    groups:
      - vmauth

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "../../../roles"
    ANSIBLE_CONFIG: ../../../ansible.cfg
verifier:
  name: ansible
