---
- name: "Systemd | Copy vminsert systemd unit file"
  ansible.builtin.template:
    src: vminsert.service.j2
    dest: "/etc/systemd/system/{{ vminsert_service_name }}.service"
    owner: root
    group: root
    mode: "0644"
  notify: Restart vminsert service

- name: "Systemd | ensure vminsert service is enabled" # noqa: no-handler
  become: true
  ansible.builtin.systemd:
    name: "{{ vminsert_service_name }}"
    enabled: true

- name: Prepare configuration dir
  ansible.builtin.file:
    state: directory
    path: "{{ vminsert_config_dir }}"
    mode: "0751"
    owner: "{{ vminsert_system_user }}"
    group: "{{ vminsert_system_group }}"

- name: Template relabel config
  ansible.builtin.template:
    src: relabeling.yaml.j2
    dest: "{{ vminsert_config_dir }}/relabel.yaml"
    owner: "{{ vminsert_system_user }}"
    group: "{{ vminsert_system_group }}"
    mode: "0600"
  when:
    - vminsert_relabel_config != ""
  notify: Restart vminsert service

- name: Configure envflag data file
  ansible.builtin.template:
    dest: "{{ vminsert_service_envflag_data_file }}"
    src: "vminsert.conf.j2"
    owner: root
    group: root
    mode: "0600"
  no_log: true
  when: vminsert_service_envflag_enabled | bool
  notify: Restart vminsert service

- name: Check envfile presence
  ansible.builtin.stat:
    path: "{{ vminsert_service_envflag_file }}"
  register: envfile_state
  when: vminsert_service_envflag_enabled | bool

- name: Setup envfile
  ansible.builtin.file:
    state: touch
    path: "{{ vminsert_service_envflag_file }}"
    owner: root
    group: root
    mode: "0600"
    access_time: preserve
  when:
    - vminsert_service_envflag_enabled | bool
    - envfile_state.stat.exists is defined and not envfile_state.stat.exists
  notify: Restart vminsert service
