---
- name: Create vminsert system group
  ansible.builtin.group:
    name: "{{ vminsert_system_group }}"
    state: present
    system: true
  when: vminsert_system_group != "root"

- name: Create vminsert system user
  ansible.builtin.user:
    name: "{{ vminsert_system_user }}"
    groups: "{{ vminsert_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
  when: vminsert_system_user != "root"

- name: Ensure existence of bin directory
  ansible.builtin.file:
    path: "{{ vminsert_bin_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install via control host
  when: vminsert_install_download_to_control
  block:
  - name: Download and unarchive vminsert release binary
    environment:
      http_proxy: "{{ vm_proxy_http }}"
      https_proxy: "{{ vm_proxy_https }}"
    ansible.builtin.unarchive:
      src: "{{ vminsert_download_url }}"
      dest: /tmp
      remote_src: yes
    delegate_to: localhost
    become: no
    when:
    - not ansible_check_mode
    - not vminsert_is_installed.stat.exists or
      vminsert_version not in vminsert_current_version.stdout

  - name: Copy vminsert binary to target host
    notify: Restart vminsert service
    ansible.builtin.copy:
      src: /tmp/vminsert-prod
      dest: "{{ vminsert_bin_dir }}/vminsert-prod"
      mode: "0751"
      owner: root
      group: "{{ vminsert_system_group }}"
    when:
    - not ansible_check_mode
    - not vminsert_is_installed.stat.exists or
      vminsert_version not in vminsert_current_version.stdout

  always:
  - name: Clear download file
    delegate_to: localhost
    become: no
    ansible.builtin.file:
      path: /tmp/vminsert-prod
      state: absent
    when:
    - not ansible_check_mode

- name: Install directly to target host
  when: not vminsert_install_download_to_control
  block:
  - name: Download and unarchive vminsert release binary
    environment:
      http_proxy: "{{ vm_proxy_http }}"
      https_proxy: "{{ vm_proxy_https }}"
    ansible.builtin.unarchive:
      src: "{{ vminsert_download_url }}"
      dest: /tmp
      remote_src: yes
      extra_opts:
      - --no-same-owner
    when:
    - not ansible_check_mode
    - not vminsert_is_installed.stat.exists or
      vminsert_version not in vminsert_current_version.stdout

  - name: Replace vminsert binary at target dir # noqa: no-changed-when
    notify: Restart vminsert service
    ansible.builtin.copy:
      src: /tmp/vminsert-prod
      dest: "{{ vminsert_bin_dir }}/vminsert-prod"
      mode: "0751"
      owner: root
      group: "{{ vminsert_system_group }}"
      remote_src: true
    when:
    - not ansible_check_mode
    - not vminsert_is_installed.stat.exists or
      vminsert_version not in vminsert_current_version.stdout

  always:
  - name: Clear download file
    ansible.builtin.file:
      path: /tmp/vminsert-prod
      state: absent
    when:
    - not ansible_check_mode

- name: Restore SELinux context for vminsert binary
  ansible.builtin.command:
    argv:
    - restorecon
    - -v
    - "{{ vminsert_bin_dir }}/vminsert-prod"
  register: restorecon_result
  changed_when: "'relabeled' in restorecon_result.stdout"
  when:
  - ansible_facts['selinux'] is defined
  - ansible_facts['selinux'].status == "enabled"
  - not ansible_check_mode
