---
vmalert_version: "{{ vic_vm_alert_version | default('v1.148.0') }}"
vmalert_enterprise: "{{ vic_vm_alert_enterprise | default(false) }}"
vmalert_license_key: "{{ vic_vm_alert_license_key | default('') }}"
vmalert_license_key_file: "{{ vic_vm_alert_license_key_file | default('') }}"
vmalert_service_name: "{{ vic_vm_alert_service_name | default('vic-vmalert') }}"

vmalert_repo_url: "{{ vic_vm_alert_repo_url | default('https://github.com/VictoriaMetrics/VictoriaMetrics') }}"
vmalert_platform: "{{ vic_vm_alert_platform | default('-linux' if vmalert_version.replace('v', '') is version('1.79.0', '>=') else '') }}"
vmalert_download_url: "{{ vic_vm_alert_download_url | default(vmalert_repo_url ~ '/releases/download/' ~ vmalert_version ~ '/vmutils' ~ vmalert_platform ~ '-' ~ go_arch ~ '-' ~ vmalert_version ~ ('-enterprise' if vmalert_enterprise else '') ~ '.tar.gz') }}"
vmalert_system_user: "{{ vic_vm_alert_system_user | default('vic_vm_alert') }}"
vmalert_system_group: "{{ vic_vm_alert_system_group | default(vmalert_system_user) }}"
vmalert_config_dir: "{{ vic_vm_alert_config_dir | default('/opt/vic-vmalert') }}"
vmalert_alertmanager_url: "{{ vic_vm_alert_alertmanager_url | default('http://localhost:9093') }}"
vmalert_datasource_url: "{{ vic_vm_alert_datasource_url | default('http://localhost:8428') }}"
vmalert_evaluation_interval: "{{ vic_vm_alert_evaluation_interval | default('30s') }}"
_vmalert_service_args_default:
  "httpListenAddr": "127.0.0.1:9431"
  "datasource.url": "{{ vmalert_datasource_url }}"
  "notifier.url": "{{ vmalert_alertmanager_url }}"
  # It is possible to use list of values to specify multiple Alertmanager endpoints, for example:
  #  "notifier.url":
  #    - "http://host1:9093"
  #    - "http://host2:9093"
  #    - "http://host3:9093"
  "evaluationInterval": "{{ vmalert_evaluation_interval }}"
vmalert_service_args: "{{ vic_vm_alert_service_args | default(_vmalert_service_args_default) }}"

vmalert_max_open_files: "{{ vic_vm_alert_max_open_files | default(2097152) }}"

vmalert_default_rules_enabled: "{{ vic_vm_alert_default_rules_enabled | default(true) }}"
vmalert_rules_config_path: "{{ vic_vm_alert_rules_config_path | default(vmalert_config_dir ~ '/rules.yml') }}"
# Great examples of alerts - https://awesome-prometheus-alerts.grep.to/rules.html
_vmalert_rules_default:
  - name: ansible managed alert rules
    rules:
      - alert: HostOutOfMemory
        expr: node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100 < 10
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "{% raw %}Host out of memory (instance {{ $labels.instance }}){% endraw %}"
          description: '{% raw %}"Node memory is filling up (< 10% left)\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"{% endraw %}'
vmalert_rules: "{{ vic_vm_alert_rules | default(_vmalert_rules_default) }}"

# Download behavior
vmalert_install_download_to_control: "{{ vic_vm_alert_install_download_to_control | default(false) }}"

# Proxy environment for downloads
vm_proxy_http: ""
vm_proxy_https: ""
