---
- name: Create VictoriaMetrics system group
  ansible.builtin.group:
    name: "{{ vmsingle_system_group }}"
    state: present
    system: true
  when: vmsingle_system_group != "root"

- name: Create VictoriaMetrics system user
  ansible.builtin.user:
    name: "{{ vmsingle_system_user }}"
    groups: "{{ vmsingle_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
  when: vmsingle_system_user != "root"

- name: Ensure existence of bin directory
  ansible.builtin.file:
    path: "{{ vmsingle_bin_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Ensure existence of VictoriaMetrics storage directory
  ansible.builtin.file:
    path: "{{ vmsingle_data_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ vmsingle_system_user }}"
    group: "{{ vmsingle_system_group }}"

- name: Install via control host
  when: vmsingle_install_download_to_control
  block:
    - name: Prepare local download paths
      delegate_to: localhost
      become: no
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /tmp/vic-single/
        - /tmp/vic-utils/
      when:
        - not ansible_check_mode
        - not vmsingle_is_installed.stat.exists or
          vmsingle_version not in vmsingle_current_version.stdout

    - name: Download and unarchive VictoriaMetrics release binary
      environment:
        http_proxy: "{{ vm_proxy_http }}"
        https_proxy: "{{ vm_proxy_https }}"
      ansible.builtin.unarchive:
        src: "{{ vmsingle_download_url }}"
        dest: /tmp/vic-single/
        remote_src: yes
        extra_opts:
          - --no-same-owner
      register: archive_downloaded
      become: no
      delegate_to: localhost
      when:
        - not ansible_check_mode
        - not vmsingle_is_installed.stat.exists or
          vmsingle_version not in vmsingle_current_version.stdout

    - name: Upload VictoriaMetrics release binary # noqa: no-handler
      ansible.builtin.copy:
        src: /tmp/vic-single/victoria-metrics-prod
        dest: "{{ vmsingle_bin_dir }}/victoria-metrics-prod"
        mode: "0751"
        owner: root
        group: "{{ vmsingle_system_group }}"
      notify: Restart VictoriaMetrics service
      when:
        - archive_downloaded is changed

    - name: Download VictoriaMetrics utils # noqa: no-handler
      become: no
      environment:
        http_proxy: "{{ vm_proxy_http }}"
        https_proxy: "{{ vm_proxy_https }}"
      ansible.builtin.unarchive:
        src: "{{ vmsingle_utils_download_url }}"
        dest: /tmp/vic-utils/
        remote_src: yes
      delegate_to: localhost
      when:
        - archive_downloaded is changed

    - name: Upload VictoriaMetrics utils release binaries # noqa: no-handler
      ansible.builtin.copy:
        src: "/tmp/vic-utils/{{ item }}"
        dest: "{{ vmsingle_bin_dir }}/{{ item }}"
        mode: "0751"
        owner: root
        group: "{{ vmsingle_system_group }}"
      when:
        - archive_downloaded is changed
      loop:
        - vmagent-prod
        - vmalert-prod
        - vmauth-prod
        - vmbackup-prod
        - vmrestore-prod

  always:
    - name: Clear download paths
      delegate_to: localhost
      become: no
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/vic-single/
        - /tmp/vic-utils/
      when:
        - not ansible_check_mode

- name: Install directly to target host
  when: not vmsingle_install_download_to_control
  block:
    - name: Prepare remote download paths
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - /tmp/vic-single/
        - /tmp/vic-utils/
      when:
        - not ansible_check_mode
        - not vmsingle_is_installed.stat.exists or
          vmsingle_version not in vmsingle_current_version.stdout

    - name: Download and unarchive VictoriaMetrics release binary
      environment:
        http_proxy: "{{ vm_proxy_http }}"
        https_proxy: "{{ vm_proxy_https }}"
      ansible.builtin.unarchive:
        src: "{{ vmsingle_download_url }}"
        dest: /tmp/vic-single/
        remote_src: yes
        extra_opts:
          - --no-same-owner
      register: archive_downloaded
      when:
        - not ansible_check_mode
        - not vmsingle_is_installed.stat.exists or
          vmsingle_version not in vmsingle_current_version.stdout

    - name: Replace VictoriaMetrics binary at target dir # noqa: no-handler
      notify: Restart VictoriaMetrics service
      ansible.builtin.copy:
        src: /tmp/vic-single/victoria-metrics-prod
        dest: "{{ vmsingle_bin_dir }}/victoria-metrics-prod"
        mode: "0751"
        owner: root
        group: "{{ vmsingle_system_group }}"
        remote_src: true
      when:
        - archive_downloaded is changed

    - name: Download and unarchive VictoriaMetrics utils # noqa: no-handler
      environment:
        http_proxy: "{{ vm_proxy_http }}"
        https_proxy: "{{ vm_proxy_https }}"
      ansible.builtin.unarchive:
        src: "{{ vmsingle_utils_download_url }}"
        dest: /tmp/vic-utils/
        remote_src: yes
      when:
        - archive_downloaded is changed

    - name: Replace VictoriaMetrics utils binaries at target dir # noqa: no-handler
      ansible.builtin.copy:
        src: "/tmp/vic-utils/{{ item }}"
        dest: "{{ vmsingle_bin_dir }}/{{ item }}"
        mode: "0751"
        owner: root
        group: "{{ vmsingle_system_group }}"
        remote_src: true
      when:
        - archive_downloaded is changed
      loop:
        - vmagent-prod
        - vmalert-prod
        - vmauth-prod
        - vmbackup-prod
        - vmrestore-prod

  always:
    - name: Clear download paths
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /tmp/vic-single/
        - /tmp/vic-utils/
      when:
        - not ansible_check_mode

- name: Restore SELinux context for VictoriaMetrics binaries
  ansible.builtin.command:
    argv:
      - restorecon
      - -v
      - "{{ vmsingle_bin_dir }}/victoria-metrics-prod"
      - "{{ vmsingle_bin_dir }}/vmagent-prod"
      - "{{ vmsingle_bin_dir }}/vmalert-prod"
      - "{{ vmsingle_bin_dir }}/vmauth-prod"
      - "{{ vmsingle_bin_dir }}/vmbackup-prod"
      - "{{ vmsingle_bin_dir }}/vmrestore-prod"
  register: restorecon_result
  changed_when: "'relabeled' in restorecon_result.stdout"
  when:
    - ansible_facts['selinux'] is defined
    - ansible_facts['selinux'].status == "enabled"
    - not ansible_check_mode
