---
- name: Converge
  hosts: all
  become: yes
  vars:
    vlsingle_data_dir: "/tmp/victoria-logs/"
    vlsingle_install_download_to_control: true
  tasks:
    - name: "Include vlsingle"
      ansible.builtin.include_role:
        name: "vlsingle"
