---
go_arch_map:
  i386: '386'
  x86_64: 'amd64'
  aarch64: 'arm64'
  armv7l: 'arm'
  armv6l: 'arm6vl'

go_arch: "{{ go_arch_map[ansible_architecture] | default(ansible_architecture) }}"

_vm_os_family_map:
  "FreeBSD": "freebsd"
  "Windows": "windows"
  "Darwin": "darwin"

vm_os_family: "{{ _vm_os_family_map[ansible_os_family] | default('linux') }}"
