---
- name: Create vmauth system group
  ansible.builtin.group:
    name: "{{ vmauth_system_group }}"
    state: present
    system: true
  when: vmauth_system_group != "root"

- name: Create vmauth system user
  ansible.builtin.user:
    name: "{{ vmauth_system_user }}"
    groups: "{{ vmauth_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
  when: vmauth_system_user != "root"

- name: Ensure existence of bin directory
  ansible.builtin.file:
    path: "{{ vmauth_bin_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Install via control host
  when: vmauth_install_download_to_control
  block:
  - name: Download and unarchive vmauth release binary
    environment:
      http_proxy: "{{ vm_proxy_http }}"
      https_proxy: "{{ vm_proxy_https }}"
    ansible.builtin.unarchive:
      src: "{{ vmauth_download_url }}"
      dest: /tmp
      remote_src: yes
    delegate_to: localhost
    become: no
    when:
    - not ansible_check_mode
    - not vmauth_is_installed.stat.exists or
      vmauth_version not in vmauth_current_version.stdout

  - name: Copy vmauth binary to target host
    notify: Restart vmauth service
    ansible.builtin.copy:
      src: /tmp/vmauth-prod
      dest: "{{ vmauth_bin_dir }}/vmauth-prod"
      mode: "0751"
      owner: root
      group: "{{ vmauth_system_group }}"
    when:
    - not ansible_check_mode
    - not vmauth_is_installed.stat.exists or
      vmauth_version not in vmauth_current_version.stdout

  always:
  - name: Clear download file
    delegate_to: localhost
    become: no
    ansible.builtin.file:
      path: /tmp/vmauth-prod
      state: absent
    when:
    - not ansible_check_mode

- name: Install directly to target host
  when: not vmauth_install_download_to_control
  block:
  - name: Download and unarchive vmauth release binary
    environment:
      http_proxy: "{{ vm_proxy_http }}"
      https_proxy: "{{ vm_proxy_https }}"
    ansible.builtin.unarchive:
      src: "{{ vmauth_download_url }}"
      dest: /tmp
      remote_src: yes
      extra_opts:
      - --no-same-owner
    when:
    - not ansible_check_mode
    - not vmauth_is_installed.stat.exists or
      vmauth_version not in vmauth_current_version.stdout

  - name: Replace vmauth binary at target dir
    notify: Restart vmauth service
    ansible.builtin.copy:
      src: /tmp/vmauth-prod
      dest: "{{ vmauth_bin_dir }}/vmauth-prod"
      mode: "0751"
      owner: root
      group: "{{ vmauth_system_group }}"
      remote_src: true
    when:
    - not ansible_check_mode
    - not vmauth_is_installed.stat.exists or
      vmauth_version not in vmauth_current_version.stdout

  always:
  - name: Clear download file
    ansible.builtin.file:
      path: /tmp/vmauth-prod
      state: absent
    when:
    - not ansible_check_mode

- name: Restore SELinux context for vmauth binary
  ansible.builtin.command:
    argv:
    - restorecon
    - -v
    - "{{ vmauth_bin_dir }}/vmauth-prod"
  register: restorecon_result
  changed_when: "'relabeled' in restorecon_result.stdout"
  when:
  - ansible_facts['selinux'] is defined
  - ansible_facts['selinux'].status == "enabled"
  - not ansible_check_mode
