---
- name: "Systemd | Copy vmselect systemd unit file"
  ansible.builtin.template:
    src: vmselect.service.j2
    dest: /etc/systemd/system/vmselect.service
    owner: root
    group: root
    mode: "0644"
  notify: Restart vmselect service

- name: "Systemd | ensure vmselect service is enabled" # noqa: no-handler
  become: true
  ansible.builtin.systemd:
    name: vmselect
    enabled: true

- name: Prepare configuration dir
  ansible.builtin.file:
    state: directory
    path: "{{ vmselect_config_dir }}"
    mode: "0751"
    owner: "{{ vmselect_system_user }}"
    group: "{{ vmselect_system_group }}"

- name: Setup environment file
  ansible.builtin.template:
    dest: "{{ vmselect_config_dir }}/vmselect.conf"
    src: "vmselect.conf.j2"
    owner: "{{ vmselect_system_user }}"
    group: "{{ vmselect_system_group }}"
    mode: "0644"
  notify: Restart vmselect service

- name: Prepare cache dir
  ansible.builtin.file:
    state: directory
    path: "{{ vmselect_cache_dir }}"
    mode: "0751"
    owner: "{{ vmselect_system_user }}"
    group: "{{ vmselect_system_group }}"
