---
- name: Create vmselect system group
  ansible.builtin.group:
    name: "{{ vmselect_system_group }}"
    state: present
    system: true
  when: vmselect_system_group != "root"

- name: Create vmselect system user
  ansible.builtin.user:
    name: "{{ vmselect_system_user }}"
    groups: "{{ vmselect_system_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    createhome: false
  when: vmselect_system_user != "root"

- name: Ensure existence of bin directory
  ansible.builtin.file:
    path: "{{ vmselect_bin_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Delete existing vmselect version if it's different.
  ansible.builtin.file:
    path: "{{ vmselect_bin_dir }}/vmselect-prod"
    state: absent
  when:
  - vmselect_is_installed.stat.exists | bool
  - vmselect_version not in vmselect_current_version.stdout

- name: Install via control host
  when: vmselect_install_download_to_control
  block:
  - name: Download and unarchive vmselect release binary
    environment:
      http_proxy: "{{ vm_proxy_http }}"
      https_proxy: "{{ vm_proxy_https }}"
    ansible.builtin.unarchive:
      src: "{{ vmselect_download_url }}"
      dest: /tmp
      remote_src: yes
    delegate_to: localhost
    become: no
    when:
    - not ansible_check_mode
    - not vmselect_is_installed.stat.exists or
      vmselect_version not in vmselect_current_version.stdout

  - name: Copy vmselect binary to target host
    notify: Restart vmselect service
    ansible.builtin.copy:
      src: /tmp/vmselect-prod
      dest: "{{ vmselect_bin_dir }}/vmselect-prod"
      mode: "0751"
      owner: root
      group: "{{ vmselect_system_group }}"
    when:
    - not ansible_check_mode
    - not vmselect_is_installed.stat.exists or
      vmselect_version not in vmselect_current_version.stdout

  always:
  - name: Clear download file
    delegate_to: localhost
    become: no
    ansible.builtin.file:
      path: /tmp/vmselect-prod
      state: absent
    when:
    - not ansible_check_mode

- name: Install directly to target host
  when: not vmselect_install_download_to_control
  block:
  - name: Download and unarchive vmselect release binary
    environment:
      http_proxy: "{{ vm_proxy_http }}"
      https_proxy: "{{ vm_proxy_https }}"
    ansible.builtin.unarchive:
      src: "{{ vmselect_download_url }}"
      dest: /tmp
      remote_src: yes
      extra_opts:
      - --no-same-owner
    when:
    - not ansible_check_mode
    - not vmselect_is_installed.stat.exists or
      vmselect_version not in vmselect_current_version.stdout

  - name: Replace vmselect binary at target dir # noqa: no-changed-when
    notify: Restart vmselect service
    ansible.builtin.copy:
      src: /tmp/vmselect-prod
      dest: "{{ vmselect_bin_dir }}/vmselect-prod"
      mode: "0751"
      owner: root
      group: "{{ vmselect_system_group }}"
      remote_src: true
    when:
    - not ansible_check_mode
    - not vmselect_is_installed.stat.exists or
      vmselect_version not in vmselect_current_version.stdout

  always:
  - name: Clear download file
    ansible.builtin.file:
      path: /tmp/vmselect-prod
      state: absent
    when:
    - not ansible_check_mode

- name: Restore SELinux context for vmselect binary
  ansible.builtin.command:
    argv:
    - restorecon
    - -v
    - "{{ vmselect_bin_dir }}/vmselect-prod"
  register: restorecon_result
  changed_when: "'relabeled' in restorecon_result.stdout"
  when:
  - ansible_facts['selinux'] is defined
  - ansible_facts['selinux'].status == "enabled"
  - not ansible_check_mode
