---
lint: |
  yamllint .
  ansible-lint .
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: vmalert-proxy-debian13
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: vmalert
  - name: vmalert-proxy-server
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-debian13}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: vmalert

provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: ../../../
verifier:
  name: ansible
