name: 'Lint'

permissions:
  contents: read
  actions: write

on:
  pull_request: { }
  push: { }

jobs:
  lint:
    name: 'Lint'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1
        with:
          persist-credentials: false

      - name: Cache .venv directory
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c  # v3.5.0
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}

      - name: Lint
        run: |
          make init-venv
          
          make lint
