name: 'Molecule Test'

permissions:
  contents: read
  actions: write

on:
  pull_request: { }
  push:
    branches:
      - master

jobs:
  test-debian:
    name: 'Test - debian'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4.3.1

      - name: Cache .venv directory
        uses: actions/cache@6f8efc29b200d32929f49075959781ed54ec270c  # v3.5.0
        with:
          path: .venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/requirements.txt') }}

      - name: Converge
        run: |
          make init-venv
          make -j$(( $(nproc) * 2 )) molecule-converge
          make -j$(( $(nproc) * 2 )) molecule-converge-integration
